export {default as App} from './App'
export {default as Header} from './Header'
export {default as Register} from './Register'
export {default as Login} from './Login'
export {default as Search} from './Search'
export {default as Home} from './Home'
export {default as PostPage} from './PostPage'
export {default as Profile} from './Profile'